name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Update .env for MySQL
      run: |
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_DATABASE=database\/database.sqlite/DB_DATABASE=laravel/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=laravel/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=laravel/' .env
    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h"127.0.0.1" --silent; do
          echo "Waiting for database connection..."
          sleep 5
        done
    - name: Run Migrations
      run: php artisan migrate --seed
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: laravel
        DB_USERNAME: laravel
        DB_PASSWORD: laravel
      run: php artisan test
