name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, xml, pdo, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate app key
      run: php artisan key:generate

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Update .env for MySQL
      run: |
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=laravel/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=laravel/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=laravel/' .env

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h127.0.0.1 --silent; do
          echo "Waiting for database connection..."
          sleep 5
        done

    - name: Run migrations
      run: php artisan migrate --seed --no-interaction --force

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs --standard=phpcs.xml

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: laravel
        DB_USERNAME: laravel
        DB_PASSWORD: laravel
      run: php artisan test
